# Generated by Django 4.2.7 on 2026-06-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('school_latitude', models.FloatField(blank=True, null=True)),
                ('school_longitude', models.FloatField(blank=True, null=True)),
                ('allowed_radius_meters', models.IntegerField(default=100, help_text='Allowed radius in meters')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='management.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('CL', 'CL (Casual Leave)'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('weekday', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Human readable location or address description', max_length=255, null=True)),
                ('distance_from_school', models.FloatField(blank=True, help_text='Distance in meters', null=True)),
                ('attendance_time', models.TimeField(default=django.utils.timezone.now)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True)),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='attendance_selfies/')),
                ('verification_method', models.CharField(choices=[('GPS', 'GPS'), ('SELFIE', 'Selfie Verification'), ('FACE', 'Face Recognition'), ('QR', 'QR Code'), ('DEVICE', 'Device Verification'), ('WIFI', 'WiFi Verification')], default='GPS', max_length=50)),
                ('wifi_bssid', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='management.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='management.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='management.teacher')),
            ],
            options={
                'ordering': ['-attendance_date', 'weekday', 'start_time', 'teacher__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('teacher', 'attendance_date'), name='unique_teacher_attendance_per_day'),
        ),
    ]
