# Generated by Django 5.2.15 on 2026-06-28 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_latitude', models.FloatField(blank=True, help_text='Latitude of the school (-90.0 to 90.0)', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('school_longitude', models.FloatField(blank=True, help_text='Longitude of the school (-180.0 to 180.0)', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('allowed_radius', models.IntegerField(default=100, help_text='Allowed attendance radius in meters', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='attendance_status',
        ),
        migrations.AlterField(
            model_name='school',
            name='allowed_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
