# Generated by Django 5.2.15 on 2026-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date', 'weekday', 'start_time', 'teacher__last_name']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('CL', 'CL (Casual Leave)'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('teacher', 'attendance_date'), name='unique_teacher_attendance_per_day'),
        ),
    ]
