# Generated by Django 4.2.7 on 2026-06-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_attendance_options_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='distance_from_school',
            field=models.FloatField(blank=True, help_text='Distance from school in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, help_text='Human readable location or address description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('GPS', 'GPS'), ('SELFIE', 'Selfie Verification'), ('FACE', 'Face Recognition'), ('QR', 'QR Code'), ('DEVICE', 'Device Verification'), ('WIFI', 'WiFi Verification')], default='GPS', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='wifi_bssid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='allowed_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='management.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='management.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('CL', 'CL (Casual Leave)'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='weekday',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
