# Generated by Django 5.2.15 on 2026-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_schoolsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='standard_class',
            field=models.CharField(blank=True, help_text='Standard/Class (STD)', max_length=100, null=True),
        ),
    ]
