# Generated by Django 5.2.15 on 2026-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_attendance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='distance_from_school',
            field=models.FloatField(blank=True, help_text='Distance in meters', null=True),
        ),
    ]
