# Generated by Django 5.2.15 on 2026-06-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_setup_default_school_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('cl', 'CL (Casual Leave)'), ('half_leave', 'Half Leave'), ('other', 'Other')], default='present', max_length=20),
        ),
    ]
