# Generated by Django 5.2.15 on 2026-06-30 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_attendance_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('cl', 'CL (Casual Leave)'), ('half_leave', 'Half Leave'), ('other', 'Other')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('GPS_SELFIE', 'GPS + Selfie'), ('GPS', 'GPS Only'), ('SELFIE', 'Selfie Only'), ('MANUAL', 'Manual')], default='GPS_SELFIE', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='allowed_radius_meters',
            field=models.IntegerField(default=500, help_text='Allowed radius in meters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='allowed_radius',
            field=models.IntegerField(default=500, help_text='Allowed attendance radius in meters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
