# Generated by Django 5.2.15 on 2026-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_attendance_approval_status_attendance_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='official_duty_reason',
            field=models.TextField(blank=True, help_text='Reason for official duty when outside school radius', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('cl', 'CL (Casual Leave)'), ('half_leave', 'Half Leave'), ('other', 'Other'), ('official_duty', 'Official Duty')], default='present', max_length=20),
        ),
    ]
